# Generated by Django 4.1.4 on 2023-01-15 18:56

import authapp.models.custom_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=150, verbose_name='project_name')),
                ('project_repo', models.FileField(blank=True, max_length=150, upload_to='', verbose_name='Project repositories')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status_complete', models.BooleanField(default=False, verbose_name='Status complete')),
                ('users_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('status_complete', models.BooleanField(default=False, verbose_name='Status complete')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
                ('users_list', models.ManyToManyField(default=authapp.models.custom_user.CustomUser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
